name: CI-4

on:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          curl -fsSL -o yqq https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64
          chmod +x yqq
          sudo mv yqq /usr/local/bin/yqq
          pipx install yq

      - name: Install Kubernetes CLI
        run: |
          curl -LO https://dl.k8s.io/release/v1.32.1/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Install gomod-gen
        run: |
          curl -fsSL -O https://github.com/appscodelabs/gomod-gen/releases/download/v0.1.6/gomod-gen-linux-amd64
          chmod +x gomod-gen-linux-amd64
          sudo mv gomod-gen-linux-amd64 /usr/local/bin/gomod-gen

      - name: Install render-gotpl
        run: |
          curl -fsSL -O https://github.com/appscodelabs/render-gotpl/releases/download/v0.1.5/render-gotpl-linux-amd64
          chmod +x render-gotpl-linux-amd64
          sudo mv render-gotpl-linux-amd64 /usr/local/bin/render-gotpl

      - name: Install gh-tools
        run: |
          curl -fsSL -O https://github.com/appscodelabs/gh-tools/releases/latest/download/gh-tools-linux-amd64
          chmod +x gh-tools-linux-amd64
          sudo mv gh-tools-linux-amd64 /usr/local/bin/gh-tools

      - name: Prepare git
        run: |
          git config --global user.name "1gtm"
          git config --global user.email "1gtm@appscode.com"

      - name: Install GitHub CLI
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          sudo mv bin/hub /usr/local/bin

      - name: Refresh repositories
        env:
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
        run: |
          GH_TOOLS_TOKEN=${GITHUB_TOKEN} gh-tools list-repos --orgs=gomodules,kmodules,kubeops,kubepack,x-helm,yawfe > repos.txt
          python3 -m venv .venv
          source .venv/bin/activate
          pipx install pyyaml
          pipx install ruamel.yaml
          ./refresh-repo.sh repos.txt
